### ISSUE TITLE
PHP 7.4 error with LDAP::login() declaration 

### ISSUE THREAD

**Issue by vignemail1** [simplesamlphp/simplesamlphp-module-ldap#14]
A Fatal error is issued when using the LDAP module with the latest PHP version available. 

Environment: PHP 7.4, Apache 2.4.41. Simplesamlphp from master branch.
```
PHP Fatal error:  Declaration of SimpleSAML\\Module\\ldap\\Auth\\Source\\LDAP::login($username, $password, ?array $sasl_args = NULL) must be compatible with SimpleSAML\\Module\\core\\Auth\\UserPassBase::login(string $username, string $password): array
```

**Comment by tvdijen** [comment]
What happens if you use the master-branch of this module? I think I may just have to tag a new 1.2 release

**Comment by vignemail1** [comment]
I do not see a tag 1.2, only 1.1.2.  
After upgrading the module to dev-master, the module is no longer recognized as 'ldap:LDAP'. 

```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 www/_include.php:17 (SimpleSAML_exception_handler)
1 vendor/symfony/error-handler/ErrorHandler.php:594 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Exception: Could not resolve 'ldap:LDAP': no class named 'SimpleSAML\Module\ldap\Auth\Source\LDAP' or 'sspmod_ldap_Auth_Source_LDAP'.
Backtrace:
7 lib/SimpleSAML/Module.php:440 (SimpleSAML\Module::resolveClass)
6 lib/SimpleSAML/Auth/Source.php:322 (SimpleSAML\Auth\Source::parseAuthSource)
5 lib/SimpleSAML/Auth/Source.php:365 (SimpleSAML\Auth\Source::getById)
4 lib/SimpleSAML/Auth/Simple.php:68 (SimpleSAML\Auth\Simple::getAuthSource)
3 lib/SimpleSAML/Auth/Simple.php:168 (SimpleSAML\Auth\Simple::login)
2 [builtin] (call_user_func_array)
1 lib/SimpleSAML/HTTP/RunnableResponse.php:70 (SimpleSAML\HTTP\RunnableResponse::send)
0 www/module.php:10 (N/A)
```

**Comment by vignemail1** [comment]
Need to change the config file to have a type 'ldap:Ldap' to get it working.

**Comment by tvdijen** [comment]
Correct.. I have to create 1.2 and add a note to have people update their config
Thanks for reporting!

**Comment by vignemail1** [comment]
And to add documentation about the new module installer workflow, specially for new installation from repo and those who need to upgrade from version before 1.16.

**Comment by tvdijen** [comment]
I certainly hope people don't update to master of SimpleSAMLphp.. It's considered unstable..
If you had used the latest stable version, you would not have had this issue..
We're working on a new major version in master, so expect bad compatibility-breaks to happen if you use it..
