### ISSUE TITLE
AttributeAddFromLDAP. Can't specify attribute placeholder in LDAP search filter

### ISSUE THREAD

**Issue by faragom** [simplesamlphp/simplesamlphp-module-ldap#20]
When setting a search filter on the AttributeAddFromLDAP authproc filter parameters, if I specify an attribute substitution placeholder as below:
```php
  'search.filter' => '(Carlicense=%PersonIdentifier%)',
```
The string can be read from `$this->search_filter` is the one below:
```php
  '(Carlicense=%)'
```
So, looks like the `"%PersonIdentifier"` string seems to be considered as a format string placeholder, and substituted with an empty string. If you add an space after the percentage, the proper string is passed to the process method:
```php
  'search.filter' => '(Carlicense=% PersonIdentifier%)',
  # '(Carlicense=% PersonIdentifier%)'
```
 It only seems to affect the strings that contain a percentage symbol followed by an alpha string, because as a temporary personal workaround, I changed the expected `'%'` placeholder symbol for a `'#'` on the code section below, and the proper string is passed and the code works fine.

https://github.com/simplesamlphp/simplesamlphp-module-ldap/blob/cda4f8b28cdc78a84cb2fe7da058606bb9c79e1a/lib/Auth/Process/AttributeAddFromLDAP.php#L105-L116

**Comment by tvdijen** [comment]
Sorry for not responding to this issue. I've just tested this with the latest version and this use-case appears to be working.
