### ISSUE TITLE
Using a hashed password in LDAP attribute 'search.password'

### ISSUE THREAD

**Issue by robegelmeer** [simplesamlphp/simplesamlphp-module-ldap#21]
**Is your feature request related to a problem? Please describe.**
We using an account to bind LDAP before we search in the LDAP. The password of this account is filled in in the authsources.php file. This password is now plain text. If we hash the password the LDAP search will not work.

**Describe the solution you'd like**
Make the search.password attribute work with a hashed value.

**Comment by tvdijen** [comment]
And how do you suggest we do that?

**Comment by robegelmeer** [comment]
I had hashed the password with bin/pwgen.php like I do for the admin account of SimpleSaml. When I filled in the hashed password the search in LDAP wasn't working. When I used the plain text password it works again. 

For the admin account a hashed password or a plain text password can be used. My suggestion would be to use the same thing for LDAP search.password attribute.

**Comment by tvdijen** [comment]
The difference is, that when an admin authenticates, we receive the password entered, we hash it, then compare the hash with the stored hash to see if it matches..

With LDAP bind, we have no user entering the password for the search service account, so we cannot hash it and compare it to any stored hash..

What you're asking is just not possible without someone interactively entering a password..

**Comment by robegelmeer** [comment]
ok, clear. The issue can be closed.
