### ISSUE TITLE
Allow AttributeAddFromLDAP failure to raise an error

### ISSUE THREAD

**Issue by jiscfoo** [simplesamlphp/simplesamlphp-module-ldap#23]
If a failure occurs in the `AttributeAddFromLDAP` authproc filter then the error is, currently, logged but processing is allowed to continue.

https://github.com/simplesamlphp/simplesamlphp-module-ldap/blob/master/lib/Auth/Process/AttributeAddFromLDAP.php#L155

```php
try {
    $entries = $ldap->searchformultiple(
    ...
} catch (Exception $e) {
    return; // silent fail, error is still logged by LDAP search
}
```

It would be useful to be able to optionally cause this error case to percolate up and **stop** the authentication flow while leaving the default behaviour as is now.

For example adding a configuration item like:
```php
"errorhandling" => "silentlycontinue"
# or
"errorhandling" => "raiseerror"
```

**Comment by tvdijen** [comment]
All processing filters will continue on non-fatal errors..   Why fail when users can still use other services that do not require ldap group membership or some service-specific attribute?

There are some other authprocs like https://github.com/simplesamlphp/simplesamlphp-module-authorize/blob/master/docs/authorize.md and https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/core/docs/authproc_cardinalitysingle.md that you can use to break out if post-conditions are not met..

**Comment by jiscfoo** [comment]
Ah, apologies for the misunderstanding. I've had a quick look at those but will try them out "for real" and either close this issue or update with the use-cases that aren't satisfied by those.

**Comment by tvdijen** [comment]
No problem! Let me know if you need any help!

**Comment by tvdijen** [comment]
How did it go? You need any help, or can I close this issue?

**Comment by jiscfoo** [comment]
Apologies for ignoring. Yes, this appears to satisfy the use-case.

**Comment by tvdijen** [comment]
No worries!
