### ISSUE TITLE
Tag clean up

### ISSUE THREAD

**Issue by dlundgren** [simplesamlphp/simplesamlphp-module-ldap#33]
It looks like some SSP tags got pulled in to the repo. It could be helpful to have the following tags removed, and hopefully packagist will also update.

- simplesamlphp-1.13.0-rc1
- v1.12.0
- v1.13.0
- v1.13.0-rc1
- v1.13.0-rc2
- v1.13.1
- v1.13.2
- v1.14.0
- v1.14.0-rc1
- v1.14.1
- v1.14.10
- v1.14.11
- v1.14.2
- v1.14.3
- v1.14.4
- v1.14.5
- v1.14.6
- v1.14.7
- v1.14.8
- v1.14.9
- v1.15.0
- v1.15.0-rc1
- v1.15.0-rc2
- v1.15.0-rc3
- v1.15.1
- v1.15.2
- v1.15.3
- v1.15.4
- v1.16.0
- v1.16.0-rc1
- v1.16.0-rc2
- v1.17.0
- v1.17.0-rc1
- v1.17.0-rc2
- v1.17.0-rc3
- v1.17.1
- v1.17.2
- v1.17.3
- v1.17.4
- v1.17.5
- v1.17.6
- v1.17.7
- v1.17.8
- v1.18.0
- v1.18.0-rc2
- v1.18.1
- v1.18.2
- v1.18.3
- v1.18.4

**Comment by tvdijen** [comment]
What the heck happened there!? 😕 Thanks for reporting this. I have removed all of them

**Comment by tvdijen** [comment]
Packagist tags have been fixed as well
