### ISSUE TITLE
Function to retrieve attributes?

### ISSUE THREAD

**Issue by grawity** [simplesamlphp/simplesamlphp-module-ldap#36]
I'm writing an authsource module which externally obtains the username (but not the password) – similar to negotiate or negotiateext – and I want to get user attributes from a normal LDAP authsource, using the exact same configuration that the authsource already has (i.e. without duplicating all settings the way negotiateext does).

For that, currently I need a copy of basically the entire ldap:Ldap `login()` function minus the final bind() call – I copy the code for config checking, searching, DN templating, attribute retrieval, etc.

It would be useful if ldap:Ldap had a public method that performed all these tasks and returned the attributes, basically like the existing login() but without a password parameter and without trying to bind as user – e.g. `getAttributes(string $username, ?array $attributes)`.

I see AttributeAddFromLDAP has much of the same duplication as well (spread across authproc and BaseFilter), it could then make use of the same interface.

(I considered an alternative of configuring the LDAP authsource to only get the uid and using AttributeAddFromLDAP authproc, to add the rest for both authsources equally, but somehow I don't like doing the same lookup twice...)

**Comment by tvdijen** [comment]
Thanks @grawity !  I think it makes sense to add the method as `protected` and have modules like `negotiate` and yours extend the ldap-authsource and implement their own `login()`-method that in turn calls the `getAttributes()`.

**Comment by grawity** [comment]
Hmm I don't think they could just extend the authsource, as ldap:Ldap is a password-based method (and derived from UserPassBase) – while e.g. the whole point of negotiate is that it's passwordless, so you can't implement login() with it.

(For example, my module's authenticate() actually just puts something like `["uid" => $_SERVER["REMOTE_USER"]]` in the user's attributes, after the webserver has already authenticated the user via mod_auth_gssapi... I'm really just re-implementing a custom version of "negotiateext", and the goal was to reuse as much of LDAP code as possible.)

I guess you mean overriding the whole LDAP authenticate() rather than login(), but still it doesn't need to inherit any of the login-page handling either... So in that case it should be a generic library function that ldap:Ldap and other modules then use.

**Comment by thijskh** [comment]
Maybe look at the radius or authx509 module. They will verify/retrieve a username via radius/x509 and will then request attributes of that user via LDAP.

**Comment by tvdijen** [comment]
@gravity Seems like what you're trying to do is re-using ldap authsource configuration for secondary purposes.. If you're not really using the ldap-authsource, it's not a good idea to 'borrow' things from it.

@thijskh Those are not the best examples.. Radius doesn't use ldap at all and authx509 still depends on the old ldap-module.

**Comment by grawity** [comment]
> @Gravity Seems like what you're trying to do is re-using ldap authsource configuration for secondary purposes..

Exactly. Such as how the ldap *authprocs* are already reusing the ldap authsource configuration for secondary purposes. Only they're currently achieving this in a very manual way.

> If you're not really using the ldap-authsource, it's not a good idea to 'borrow' things from it.

The plan is to use both depending on some conditions (like how negotiateext has fallback depending on a cookie), so yes, it's actually being used as an authsource on its own.

For example, suppose you set up ldap + negotiateext (which can also get attributes from LDAP) – but the thing is, negotiateext has its own LDAP server configuration, which is subtly different from the ldap authsource configuration, the parameters are named differently, the search logic isn't quite the same, etc.

In contrast, if you have an ldap:Ldap authsource and an ldap:AttributeGroups authproc, you currently *don't* have to duplicate all settings to the authproc – you can already tell it "just take all settings from this authsource please".

So what I was trying to do is reuse existing code so that the same LDAP server configuration and code could be used both by the ldap authsource itself and by other components. It doesn't need to be in the authsource, necessarily, the goal is just to have it unified *somewhere* that all the mentioned modules could use.

**Comment by tvdijen** [comment]
@grawity I think the linked PR solves a great part of your issue.. Care to check it out?

**Comment by tvdijen** [comment]
I'm not sure we need a separate function to retrieve attributes, since, once you have a Connection-object, you can simply do a one-liner search to retrieve en LdapEntry.

**Comment by grawity** [comment]
Thanks, haven't yet had a chance to have a deeper look but this looks close to what I wanted.

> I'm not sure we need a separate function to retrieve attributes, since, once you have a Connection-object, you can simply do a one-liner search to retrieve en LdapEntry.

True, but it would still be useful as the overall goal is to mimic the results of the LDAP authsource (i.e. given a username, to search the same baseDN using the same filter and to retrieve the same attributes).

**Comment by tvdijen** [comment]
Added the getAttributes too.. If you're happy with it, I'll merge & tag `v2.1.0`
