### ISSUE TITLE
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

### ISSUE THREAD

**Issue by codedev900** [simplesamlphp/simplesamlphp-module-ldap#38]
I'm trying to connect LDAP with SimpleSAMLphp, but I keep getting an error message:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:20 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Error: Call to undefined function SimpleSAML\Module\ldap\Auth\ldap_connect()
Backtrace:
6 modules/ldap/lib/Auth/Ldap.php:96 (SimpleSAML\Module\ldap\Auth\Ldap::__construct)
5 modules/ldap/lib/ConfigHelper.php:201 (SimpleSAML\Module\ldap\ConfigHelper::login)
4 modules/ldap/lib/Auth/Source/LDAP.php:58 (SimpleSAML\Module\ldap\Auth\Source\LDAP::login)
3 modules/core/lib/Auth/UserPassBase.php:318 (SimpleSAML\Module\core\Auth\UserPassBase::handleLogin)
2 modules/core/www/loginuserpass.php:84 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

Your help would be much appreciated.

**Comment by thijskh** [comment]
DId you install PHP's ldap module?

**Comment by tvdijen** [comment]
Yeah, that's it.. You are missing the PHP ldap-extension

**Comment by codedev900** [comment]
I tried running the install command "apt install php-ldap" on the docker image, but I got the following error:

# apt install php-ldap
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package php-ldap is a virtual package provided by:
  php7.4-ldap 7.4.33-1+deb11u1 [Not candidate version]
  php7.4-ldap 7.4.30-1+deb11u1 [Not candidate version]

E: Package 'php-ldap' has no installation candidate

How do I install or enable the php-ldap on the simplesamlphp docker image?

**Comment by tvdijen** [comment]
I don't know.. We don't maintain any docker container. Perhaps you can ask the author?
