### ISSUE TITLE
Please bump simplesamlphp/assert

### ISSUE THREAD

**Issue by MichaelRoosz** [simplesamlphp/simplesamlphp-module-ldap#43]
Since this commit 
https://github.com/simplesamlphp/simplesamlphp/commit/70813b3af2b3d0bd600a8659b08aae31cf197d4b
compatbility with simplesamlphp is broken.

Please bump it also here - I am forced to use dev-master currently, because it is the only version with support for symfony 6

**Comment by tvdijen** [comment]
Closed in 16f314c328499186d0b1f801920bc904ec7f09f5
