### ISSUE TITLE
Unexpectedly returns no value when attributes is set to NULL

### ISSUE THREAD

**Issue by seieric** [simplesamlphp/simplesamlphp-module-ldap#44]
When "attributes" of ldap configuration is set to NULL, this module is supposed to provide all the ldap attributes to SP.
However, it returns **NO** ldap attributes under the circumstance right now.

### Why?
I found evaluation of "attributes" configuration in [src/Auth/Source/Ldap.php](https://github.com/simplesamlphp/simplesamlphp-module-ldap/blob/16f314c328499186d0b1f801920bc904ec7f09f5/src/Auth/Source/Ldap.php#L182).
Here is what the process is doing when "attributes" is set to NULL

1. Try to get "attributes" configuration by using getOptionalValue
2. getOptionalValue func returns the default value supplied which is ```$this->ldapConfig->hasValue('attributes') ? null: []``` because "attributes" is NULL.
3. $this->ldapConfig->hasValue func returns false cause its implementation is ```return array_key_exists($name, $this->configuration) && !is_null($this->configuration[$name]);```. (refer to [simplesamlphp/simplesamlphp:src/SimpleSAML/Configuration.php](https://github.com/simplesamlphp/simplesamlphp/blob/70813b3af2b3d0bd600a8659b08aae31cf197d4b/src/SimpleSAML/Configuration.php#L417))
4. Therefore $attributes is set to empty array.
5. ```$attributes === null``` ends up to false even though original configuration value is NULL. And no ldap attributes are returned.

### Solution

Here is a brief solution:

```PHP
    private function processAttributes(Entry $entry): array
    {
        $attributes = $this->ldapConfig->getOptionalValue(
            'attributes',
            // If specifically set to NULL return all attributes, if not set at all return nothing (safe default)
            // $this->ldapConfig->hasValue('attributes') ? null: [],
           in_array('attributes', $this->ldapConfig->getOptions()) ? null: [],
        );
[...]
```

### My environment
- PHP 8.1.2
- SimpleSAMLphp 2.0.0

**Comment by tvdijen** [comment]
This has already been fixed in #40 and released in v2.1.4
