### ISSUE TITLE
2.0.5 | Unable to authenticate user to AD using e-mail address and ldaps protocol

### ISSUE THREAD

**Issue by Ferdelances245** [simplesamlphp/simplesamlphp-module-ldap#47]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
Unable to authenticate user to AD using e-mail address and ldaps protocol

**To Reproduce**
1. Create an ldaps auth for active directory
2. Go to admin website
3. Click on test
4. Test your ldaps authentification for AD
5. The mail attribute causes connection failure but other attributs will working like sAMAccountName or userprincipalname
6. The error not appair in log file

**Expected behavior**
Authentification success

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

**Additional context**
'search.attributes' => ['sAMAccountName', 'mail'],

**Comment by Ferdelances245** [comment]
Exactly.

Here authsource file :

` 'ad-ldap' => [
        'ldap:Ldap',
        'connection_string' => 'ldaps://controler.domain',
        'ldap.port' => 'SSL PORT FOR LADPS',
        'encryption' => 'ssl',
        'version' => 3,
        'ldap.debug' => true,
        'options' => [
            'referrals' => 0x00,

            'network_timeout' => 3,
        ],
        'connector' => '\SimpleSAML\Module\ldap\Connector\ActiveDirectory',
        'attributes' => ['sAMAccountName', 'mail', 'displayName', 'memberOf'],
        'attributes.binary' => [
            'jpegPhoto',
            'objectGUID',
            'objectSid',
            'mS-DS-ConsistencyGuid'
        ],
        'dnpattern' => 'uid=%username%,ou=people,dc=example,dc=org',
        'search.enable' => TRUE,
        'search.base' => ['DC=do,DC=main'],
        'search.scope' => 'sub',
        'search.attributes' => ['sAMAccountName', 'mail'],
        'search.username' => 'user@domain',
        'search.password' => 'password'
    ]
  
  
  
  ____
  
  Fun fact. I can get attribute mail from AD if i use sAMAccountName but not login with mail.
  
  ___
  
  If put the wrong password, i have the unsuccessfull error in my log file

**Comment by tvdijen** [comment]
Any special characters or diacritics in your email address?

**Comment by Ferdelances245** [comment]
i have a "." in the mail prefix

firstname.lastname@domain.org

**Comment by Ferdelances245** [comment]
"You get a 'Incorrect username or password' without an entry for 'Unsuccessful login' in the logs?"

=> Yes exactly. I have the error in the log only if i put a fake password

"Can you try to revert the LDAP-module to 2.1.6? Maybe a recent change related to 'escaping user-input' causes this issue."

I'll test your solution on Tuesday if I can, I won't have access to my VM until then. Thanks for your help

**Comment by tvdijen** [comment]
Any update @Ferdelances245 ?

**Comment by tvdijen** [comment]
Any news @Ferdelances245 ?
