### ISSUE TITLE
issue on authentication using LdapMulti

### ISSUE THREAD

**Issue by fulvioscorza** [simplesamlphp/simplesamlphp-module-ldap#50]
Hi,
I'm running SimpleSaml 2.1.1

User authentication fails when using  'ldap:LdapMulti', instead of 'ldap:Ldap' (last one works )

Log shows as follow:
WARNING [8356a5701c] Wrong stage in state. Was '\SimpleSAML\Module\core\Auth\UserPassOrgBase.state', should be '\SimpleSAML\Module\core\Auth\UserPassBase.state'.

This seems to come  from src/SimpleSAML/Auth/State.php called from Login.php

in saml20-idp-hostd.php  I've following statement (only  ldap auth calling showed)
        'auth' => 'multildap',

Content of config/authsources.php is :

        'myldap' => [
        'ldap:Ldap',
                'connection_string' => 'ldaps://[1.2.3.4](http://1.2.3.4/)',
                'encryption' => 'ssl',
                'version' => 3,
                'debug' => true,
                'options' => [
                        ],
                 'connector' => '\SimpleSAML\Module\ldap\Connector\Ldap',
                'attributes' => null,
                'search.enable' => true,
                'search.base' =>        [
                        'dc=abc,dc=it',
                        ],
                'search.scope' => 'sub',
                'search.attributes' => array('uid'),
                'search.username' => 'cn=bind,dc=abc,dc=it',
                'search.password' => 'mypass',
        ],

    'multildap' => [
        'ldap:LdapMulti',
        'username_organization_method' => 'force',
        'include_organization_in_username' => true,
        'mapping' => [
            '[abc.it](http://abc.it/)' => [
                'authsource' => 'myldap',
            ],

            'students' => [
                //'description' => 'Students',
                'authsource' => 'example-ldap-2',
            ],
        ],
    ],
];

If in saml20-idp.hosted i use "myldap" instead of "multildap" is ok.
User is in the form   [x...@abc.it](https://groups.google.com/)

Same configuration works on 1.19 release (obviously with syntax release differences)

**Comment by geralt** [comment]
Hi @fulvioscorza,

 you can bypass the problem changing **UserPassOrgBase** class code. From:

```
    /**
     * The string used to identify our states.
     */
    public const STAGEID = '\SimpleSAML\Module\core\Auth\UserPassOrgBase.state';

    /**
     * The key of the AuthId field in the state.
     */
    public const AUTHID = '\SimpleSAML\Module\core\Auth\UserPassOrgBase.AuthId';

    /**
     * The key of the OrgId field in the state, identifies which org was selected.
     */
    public const ORGID = '\SimpleSAML\Module\core\Auth\UserPassOrgBase.SelectedOrg';
```

To:

```
/**
     * The string used to identify our states.
     */
    public const STAGEID = '\SimpleSAML\Module\core\Auth\UserPassBase.state';

    /**
     * The key of the AuthId field in the state.
     */
    public const AUTHID = '\SimpleSAML\Module\core\Auth\UserPassBase.AuthId';

    /**
     * The key of the OrgId field in the state, identifies which org was selected.
     */
    public const ORGID = '\SimpleSAML\Module\core\Auth\UserPassBase.SelectedOrg';
```

Maybe this isn't the correct way to solve the problem but it let you continue working.

**Comment by fulvioscorza** [comment]
Hi Jorge,

I've tried with workaround suggested and it works.
It's better than mine.
many thanks.
by
fs


Il giorno ven 1 mar 2024 alle ore 13:22 Jorge Hoya ***@***.***>
ha scritto:

**Comment by tvdijen** [comment]
I think I finally found the issue here.
The form-post is always sent to `module/core/loginuserpass` instead of `module/core/loginuserpassorg` because it is [hardcoded](https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-2.2/modules/core/templates/loginuserpass.twig#L40C34-L40C39) in the template.

@geralt Would you be able to verify that changing the template also fixes your issue?

**Comment by geralt** [comment]
@tvdijen Verified, it works fine!

**Comment by tvdijen** [comment]
Thanks for testing! I will merge & release soon!
