### ISSUE TITLE
LDAP server hostname in authsources.php

### ISSUE THREAD

**Issue by maarbu** [simplesamlphp/simplesamlphp-module-ldap#6]
When specifying a single LDAP server in the hostname directive, you don't need to put in ldap:// or ldaps://. `'hostname' => 'ldapserver.example.com',` will work fine.  However, if you add a failover server by separating with a space like this: `'hostname' => 'ldapserver1.example.com ldapserver2.example.com',` this will cause a 500 error.  This is remedied by putting in ldap:// or ldaps:// in front of each server name.  I ran across this issue when upgrading.  It used to work the first way.

I haven't sussed out exactly what upgrade caused the issue.  I upgraded PHP and OpenLDAP at the same time, my guess is OpenLDAP.

Should there be code added to check for the ldaps:// or ldap:// prefix or is it assumed that people will put this in by default?

**Comment by tvdijen** [comment]
Time has catched up with us.. This module has been rewriten to use `symfony/ldap` and that comes with the implication that all LDAP-sources have to be addressed in URI-format using the `connection_string` setting.
